spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: git@github.com:ppyang010/spring-cloud-config-repo.git
          username: 644724460@qq.com
          password: ccy6482082
server:
  port: 7730


