spring:
  application:
    name: spring-cloud-eureka
server:
  port: 7700
eureka:
  client:
    #  表示是否将自己注册到Eureka Server，默认为true。
    register-with-eureka: false
    #  表示是否从Eureka Server获取注册信息，默认为true。
    fetch-registry: false
    serviceUrl:
      defaultZone: http://127.0.0.1:7700/eureka/
  server:
    #    关闭自我保护机制
    enable-self-preservation: false
    #    是否使用 readOnlyCacheMap
#    useReadOnlyResponseCache: false