spring:
  profiles:
    active: dev0
#    include: redis
server:
  port: 9000

---
spring:
  profiles: dev0
  application:
    name: could-gateway
  #    使用配置文件方式配置路由信息
  cloud:
    gateway:
      discovery:
        locator:
          #        是否开始基于服务发现的路由规则
          enabled: true
          #          当注册中心为eureka时 设置为true表示开启用小写的serviceId进行基于服务路由的转发
          lower-case-service-id: true
      routes:
        - id: my_filter_factory
#        http://127.0.0.1:9000/my_filter_factory/gateway/target
          uri: lb://could-eureka-consumer/
          filters:
            - StripPrefix=1
            - RequestTime=false
          predicates:
            - Path=/my_filter_factory/**
        - id: yml_lb
          uri: lb://could-eureka-consumer/
          filters:
            - StripPrefix=1
          predicates:
            - Path=/yml_lb/**
        - id: baidu_route
          uri: http://www.baidu.com:80/
          predicates:
            - Path=/baidu
        - id: hystrix_lb   #hystrix + lb
          uri: lb://could-eureka-consumer/
          predicates:
            - Path=/hystrix_lb/**
          filters:
            - name: Hystrix
              args: #指定hystrix command的名称，及fallbackUri，注意fallbackUri要以forward开头
                name: fallbackcmd
                fallbackUri: forward:/fallback

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:7700/eureka
logging:
  level:
    org.springframework.cloud.gateway: debug
