spring:
  application:
    name: could-eureka-consumer
  main:
      allow-bean-definition-overriding: true #允许多个feignclient 使用通过服务name

server:
  port: 7720
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:7700/eureka
feign:
   hystrix:
     enabled: true

#用来测试从config的获取参数
form:
  remark: from-consumer
