spring:
  application:
    name: could-eureka-consumer
  main:
    allow-bean-definition-overriding: true #允许多个feignclient 使用通过服务name

server:
  port: 7720
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:7700/eureka
feign:
  hystrix:
    enabled: true
#   httpclient:
#     enabled: true

#用来测试从config的获取参数
form:
  profile: local-default
  remark: from-consumer
# 对应默认配置 com.netflix.hystrix.HystrixCommandProperties
hystrix:
  threadpool:
    default:
      coreSize: 10 #线程池的核心线程数 默认10
      maxQueueSize: -1 #BlockingQueue的最大队列数，默认值-1 ,-1表示不等待直接拒绝,测试表明线程池使用直接决绝策略
      #最大线程数量
      maximumSize: 20
      #      允许maximumSize大于coreSize，只有配了这个值maximumSize才有意义(才生效) 默认false
      allowMaximumSizeToDivergeFromCoreSize: false
      #      超过这个时间多于coreSize数量的线程会被回收，只有maximumsize大于coreSize，这个值才有意义 默认1 单位分钟
      keepAliveTimeMinutes: 1
      #即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝，默认值5
      #任务队列中存储的任务数量超过这个值，线程池拒绝新的任务。这跟maxQueueSize本来是一回事，只是受限于hystrix的实现方式maxQueueSize不能动态配置，所以有了这个配置。
      queueSizeRejectionThreshold: 800
    #     设置定制线程池核心线程数
    xxxPool:
      coreSize: 1
      maximumSize: 2
      maxQueueSize: -1 #BlockingQueue的最大队列数，默认值-1 ,-1表示不等待直接拒绝,测试表明线程池使用直接决绝策略
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000 #请求超时时间
      circuitBreaker: #熔断器相关配置
        enabled: true   #是否启动熔断器，默认为true，false表示不要引入Hystrix。
        requestVolumeThreshold: 10     #启用熔断器功能窗口时间内的最小请求数，建议设置为 QPS * 窗口秒数 * 60%。
        sleepWindowInMilliseconds: 5000    #所以此配置的作用是指定熔断器打开后多长时间内允许一次请求尝试执行，官方默认配置为5秒。
        errorThresholdPercentage: 20   #窗口时间内超过50%的请求失败后就会打开熔断器将后续请求快速失败掉,默认配置为50
      metrics:
        rollingStats:
          timeInMilliseconds: 20000 #此配置项指定了窗口的大小，单位是 ms，默认值是 1000，即一个滑动窗口默认统计的是 1s 内的请求数据.该时间也是断路器判断健康度时需要收集信息的持续时间

    #    为方法定制线程池 线程池名称
    FallbackTestFeignClient#errorThreadNotEnough():
      threadPoolKeyOverride: xxxPool
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000 #请求超时时间




#ribbon:
##  ServerListUpdaterClassName: com.netflix.niws.loadbalancer.EurekaNotificationServerListUpdater
#
#
#could-eureka-producer:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule